site_name: "Intelligent Media and Vision Laboratory"
site_url: https://eitech.cuhk.edu.cn
copyright: "Copyright &copy; IMVL 2025 All rights reserved. <span style='color: #161616;'>Designed by YUAN Mingqi.</span>"
theme:
  name: material
  custom_dir: docs/overrides/
  include_search_page: false
  search_index_only: true
  logo: assets/images/eit_logo.svg
  favicon: favicon.ico
  palette:
    - scheme: white
      primary: white
      accent: white
  
  features:
    - toc.integrate
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.select
    - content.code.copy
    - content.code.select

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/banner.css


extra_javascript:
  - assets/stylesheets/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/banner.js

markdown_extensions:
  - sane_lists
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra:
  generator: false
  social: 
    - icon: fontawesome/solid/envelope
      link: simonpun@cuhk.edu.cn
    - icon: fontawesome/solid/phone
      link: +86-0755-23519520
nav:
  - Home: 
    - "2025": index.md
    # - "2024": news/2024.md
    # - "2023": news/2023.md
    # - "2022": news/2022.md
  - Research: research.md
  - Publications: pubs.md
  - Members: members.md
  - About: contact.md

plugins:
  - macros